alias python="python3"
alias pip="pip3"
alias charm="pycharm"
# Zoxide interactive jumpers
alias j="zoxide query -i"
alias zi='cd "$(zoxide query -i)"'
alias cdi='zoxide query --interactive'
alias nvconf='cd ~/.config/nvim && nvim'
alias vim="nvim"
alias zconf="cd && nvim ~/.zshrc"
alias vzsh="cd ~/.zsh && nvim"
alias desk='~/Desktop'
alias dcs='~/Documents'
alias dws='~/Downloads'
alias ghstconf='cd ~/Library/Application\ Support/com.mitchellh.ghostty && nvim config'
alias moodle='~/Scripts/moodle/.venv/bin/python3 ~/Scripts/moodle/main.py'
alias tau='~/Scripts/moodle/.venv/bin/python3 ~/Scripts/moodle/main.py tau'
alias semester='open ~/obsidian/TAU'
hash -d icloud="$HOME/Library/Mobile Documents/com~apple~CloudDocs"
hash -d vault="$HOME/Library/Mobile Documents/iCloud~md~obsidian/Documents"
alias aspace='df -h / | tail -1 | awk "{print \$4}"'
alias soffice-convert='soffice --headless --convert-to'
alias clean-cache='sudo rm -rf /private/var/folders/*/*/X/*.code_sign_clone'
alias ltree='lsd --tree'
alias TRASH="~/Library/Mobile\ Documents/.Trash"
alias mtau='python ~/Scripts/mv-tau/main.py'
